
Total Nitrogen CALC (mg/l): IIf([NITROGEN, TOTAL (MG/L AS N)] Is Null,[NITRITE, TOTAL (MG/L AS N)]+[NITRATE, TOTAL (MG/L AS N)]+[NITROGEN, TOTAL KJELDAHL (MG/L AS N)],[NITROGEN, TOTAL (MG/L AS N)])

#AMMONIA, TOTAL (MG/L AS N)- 2016 Raw Data
#AMMONIA, TOTAL Com - 2016 Raw Data
#WQS Acute NH3-N: IIf([Field Ph] Is Null Or [AMMONIA, TOTAL (MG/L AS N)] Is Null,Null,IIf([STDCLASS]="5" Or [STDCLASS]="6",(0.275/(1+10^(7.204-[Field Ph])))+(39/(1+10^([Field Ph]-7.204))),IIf([STDCLASS] Is Null,Null,(0.411/(1+10^(7.204-[Field Ph])))+(58.4/(1+10^([Field Ph]-7.204))))))
#NH3-N Assess: IIf([Field Ph] Is Null Or [AMMONIA, TOTAL (MG/L AS N)] Is Null Or [STDCLASS] Is Null,Null,IIf([AMMONIA, TOTAL (MG/L AS N)]>[WQS Acute NH3-N],"EXCEEDS","FS"))
#NITRITE, TOTAL (MG/L AS N) - raw
#NITRATE, TOTAL Com- raw
#Nitrate Assess: IIf([SPEC_STD] Is Null Or [NITRATE, TOTAL (MG/L AS N)] Is Null Or [SPEC_STD] Not Like "*PWS*" Or [SPEC_STD] Not Like "PWS*",Null,(IIf([SPEC_STD] Like "*PWS*" And [NITRATE, TOTAL (MG/L AS N)]>10 Or [SPEC_STD] Like "PWS*" And [NITRATE, TOTAL (MG/L AS N)]>10,"EXCEEDS","FS")))
NITROGEN, TOTAL KJELDAHL (MG/L AS N)- raw
NITROGEN, TOTAL KJELDAHL Com- raw
PHOSPHORUS, TOTAL Com-raw
PHOSPHORUS, TOTAL Com- raw
TPhos Assess: IIf([PHOSPHORUS, TOTAL (MG/L AS P)] Is Null,Null,IIf([STA_TYPE]="Stream" And [PHOSPHORUS, TOTAL (MG/L AS P)]>0.2,"EXCDS",IIf([STA_TYPE]="Lake" And [PHOSPHORUS, TOTAL (MG/L AS P)]>0.05,"EXCDS","FS")))
#CHLORIDE, TOTAL (MG/L)- raw
#CHLORIDE, TOTAL Com- raw
#WQS Acute/PWS CHLORIDE (mg/l): IIf([CHLORIDE, TOTAL (MG/L)] Is Null,Null,IIf([SPEC_STD] Like "PWS*" And ([CHLORIDE, TOTAL (MG/L)]>250),"EXCEEDS",IIf([SPEC_STD] Like "PWS*" And ([CHLORIDE, TOTAL (MG/L)]<250),"Full Support",IIf([CHLORIDE, TOTAL (MG/L)]>860,"EXCEEDS","FS"))))
FECAL COLIFORM (MPNECMED/100 ML)- raw
FECAL COLIFORM 31615 Com- raw
FC MEMBRANE FIL METH- raw
FC MEMBRANE FIL METH Com- raw
FECAL Assess: IIf([FC MEMBRANE FIL METH] Is Null,Null,IIf([FC MEMBRANE FIL METH]>400,"EXCEEDS","FS"))
#ECOLI Assess: IIf([Ecoli N/100 ML] Is Null,Null,IIf([Ecoli N/100 ML]>235,"EXCEEDS","FS"))

Chloro A Assess: IIf([CHLOROPHYLL A COR (UG/L)] Is Null,Null,IIf([CHLOROPHYLL A COR (UG/L)]>50,"EXCEEDS","FS"))